# Generated by Django 4.0.4 on 2022-05-23 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('level', models.IntegerField()),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=2)),
                ('status', models.CharField(choices=[('a', 'active'), ('i', 'inactive')], default='active', max_length=10)),
                ('department', models.CharField(blank=True, choices=[('General', 'General'), ('CS', 'CS'), ('IS', 'IS'), ('AI', 'AI'), ('DS', 'DS'), ('IT', 'IT')], max_length=50)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='Female', max_length=7)),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
