# Generated by Django 4.0.4 on 2022-05-23 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_login_register_alter_student_gpa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='name',
            new_name='username',
        ),
    ]
