# Generated by Django 4.0.4 on 2022-05-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_name_login_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='name',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
