# Generated by Django 4.0.4 on 2022-05-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_name_register_email_alter_login_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('a', 'active'), ('i', 'inactive')], default='active', max_length=10, null=True),
        ),
    ]
