# Generated by Django 4.0.4 on 2022-05-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('CS', 'CS'), ('IS', 'IS'), ('AI', 'AI'), ('DS', 'DS'), ('IT', 'IT')], max_length=50, null=True),
        ),
    ]
