# Generated by Django 4.0.4 on 2022-05-24 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gpa',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
